cluster: master
driver: docker
namespace: brewery
containers:
#TUTTO HIGH
  - name: gateway
    cpu: "3"
    memory: "4Gi"
  - name: aggregator
    cpu: "2"
    memory: "2Gi"
  - name: analyzer
    cpu: "1800m"
    memory: "1500Mi"
  - name: data-gather-olbia
    cpu: "2"
    memory: "2Gi"
  - name: data-gather-torino
    cpu: "2"
    memory: "2Gi"
  - name: mongodb-batch-olbia
    cpu: "1"
    memory: "2Gi"
  - name: mongodb-batch-torino
    cpu: "1"
    memory: "2Gi"
  - name: mongodb-history
    cpu: "1"
    memory: "2Gi"