% Deployment
deployedTo(aggregator, large, worker3).
deployedTo(analyzer, large, worker2).
deployedTo(data_gather_olbia, large, worker1).
deployedTo(data_gather_torino, large, worker3).
deployedTo(gateway, large, main).
deployedTo(mongodb_batch_olbia, medium, worker3).
deployedTo(mongodb_batch_torino, medium, worker2).
deployedTo(mongodb_history, medium, worker2).

% Components failures
unreachable(aggregator, 31).
unreachable(aggregator, 32).
unreachable(aggregator, 33).
unreachable(aggregator, 34).
unreachable(aggregator, 35).
unreachable(aggregator, 36).
unreachable(aggregator, 37).
unreachable(aggregator, 38).
unreachable(aggregator, 39).
unreachable(aggregator, 40).
unreachable(aggregator, 41).
unreachable(aggregator, 42).
unreachable(aggregator, 43).
unreachable(aggregator, 44).
unreachable(aggregator, 45).
unreachable(aggregator, 46).
unreachable(aggregator, 47).
unreachable(aggregator, 48).
unreachable(aggregator, 49).
unreachable(aggregator, 50).
unreachable(aggregator, 51).
unreachable(aggregator, 52).
unreachable(aggregator, 53).
unreachable(aggregator, 54).
unreachable(aggregator, 55).
unreachable(aggregator, 56).
unreachable(aggregator, 57).
unreachable(aggregator, 58).
unreachable(aggregator, 59).
unreachable(aggregator, 60).
unreachable(aggregator, 61).
unreachable(aggregator, 62).
unreachable(aggregator, 63).
unreachable(aggregator, 64).
unreachable(aggregator, 65).
unreachable(aggregator, 66).
unreachable(aggregator, 67).
unreachable(aggregator, 68).
unreachable(aggregator, 69).
unreachable(aggregator, 70).
unreachable(aggregator, 71).
unreachable(aggregator, 72).
unreachable(aggregator, 73).
unreachable(aggregator, 74).
unreachable(aggregator, 75).
unreachable(aggregator, 76).
unreachable(aggregator, 77).
unreachable(aggregator, 78).
unreachable(aggregator, 79).
unreachable(aggregator, 80).
unreachable(aggregator, 81).
unreachable(aggregator, 82).
unreachable(aggregator, 83).
unreachable(aggregator, 84).
unreachable(aggregator, 85).
unreachable(aggregator, 86).
unreachable(aggregator, 87).
unreachable(aggregator, 88).
unreachable(aggregator, 89).
unreachable(aggregator, 90).
unreachable(aggregator, 91).
unreachable(aggregator, 92).
unreachable(aggregator, 93).
unreachable(aggregator, 94).
unreachable(aggregator, 95).
unreachable(aggregator, 96).
unreachable(aggregator, 97).
unreachable(aggregator, 98).
unreachable(data_gather_torino, 31).
unreachable(data_gather_torino, 32).
unreachable(data_gather_torino, 33).
unreachable(data_gather_torino, 34).
unreachable(data_gather_torino, 35).
unreachable(data_gather_torino, 36).
unreachable(data_gather_torino, 37).
unreachable(data_gather_torino, 38).
unreachable(data_gather_torino, 39).
unreachable(data_gather_torino, 40).
unreachable(data_gather_torino, 41).
unreachable(data_gather_torino, 42).
unreachable(data_gather_torino, 43).
unreachable(data_gather_torino, 44).
unreachable(data_gather_torino, 45).
unreachable(data_gather_torino, 46).
unreachable(data_gather_torino, 47).
unreachable(data_gather_torino, 48).
unreachable(data_gather_torino, 49).
unreachable(data_gather_torino, 50).
unreachable(data_gather_torino, 51).
unreachable(data_gather_torino, 52).
unreachable(data_gather_torino, 53).
unreachable(data_gather_torino, 54).
unreachable(data_gather_torino, 55).
unreachable(data_gather_torino, 56).
unreachable(data_gather_torino, 57).
unreachable(data_gather_torino, 58).
unreachable(data_gather_torino, 59).
unreachable(data_gather_torino, 60).
unreachable(data_gather_torino, 61).
unreachable(data_gather_torino, 62).
unreachable(data_gather_torino, 63).
unreachable(data_gather_torino, 64).
unreachable(data_gather_torino, 65).
unreachable(data_gather_torino, 66).
unreachable(data_gather_torino, 67).
unreachable(data_gather_torino, 68).
unreachable(data_gather_torino, 69).
unreachable(data_gather_torino, 70).
unreachable(data_gather_torino, 71).
unreachable(data_gather_torino, 72).
unreachable(data_gather_torino, 73).
unreachable(data_gather_torino, 74).
unreachable(data_gather_torino, 75).
unreachable(data_gather_torino, 76).
unreachable(data_gather_torino, 77).
unreachable(data_gather_torino, 78).
unreachable(data_gather_torino, 79).
unreachable(data_gather_torino, 80).
unreachable(data_gather_torino, 81).
unreachable(data_gather_torino, 82).
unreachable(data_gather_torino, 83).
unreachable(data_gather_torino, 84).
unreachable(data_gather_torino, 85).
unreachable(data_gather_torino, 86).
unreachable(data_gather_torino, 87).
unreachable(data_gather_torino, 88).
unreachable(data_gather_torino, 89).
unreachable(data_gather_torino, 90).
unreachable(data_gather_torino, 91).
unreachable(data_gather_torino, 92).
unreachable(data_gather_torino, 93).
unreachable(data_gather_torino, 94).
unreachable(data_gather_torino, 95).
unreachable(data_gather_torino, 96).
unreachable(data_gather_torino, 97).
unreachable(data_gather_torino, 98).
unreachable(mongodb_batch_olbia, 31).
unreachable(mongodb_batch_olbia, 32).
unreachable(mongodb_batch_olbia, 33).
unreachable(mongodb_batch_olbia, 34).
unreachable(mongodb_batch_olbia, 35).
unreachable(mongodb_batch_olbia, 36).
unreachable(mongodb_batch_olbia, 37).
unreachable(mongodb_batch_olbia, 38).
unreachable(mongodb_batch_olbia, 39).
unreachable(mongodb_batch_olbia, 40).
unreachable(mongodb_batch_olbia, 41).
unreachable(mongodb_batch_olbia, 42).
unreachable(mongodb_batch_olbia, 43).
unreachable(mongodb_batch_olbia, 44).
unreachable(mongodb_batch_olbia, 45).
unreachable(mongodb_batch_olbia, 46).
unreachable(mongodb_batch_olbia, 47).
unreachable(mongodb_batch_olbia, 48).
unreachable(mongodb_batch_olbia, 49).
unreachable(mongodb_batch_olbia, 50).
unreachable(mongodb_batch_olbia, 51).
unreachable(mongodb_batch_olbia, 52).
unreachable(mongodb_batch_olbia, 53).
unreachable(mongodb_batch_olbia, 54).
unreachable(mongodb_batch_olbia, 55).
unreachable(mongodb_batch_olbia, 56).
unreachable(mongodb_batch_olbia, 57).
unreachable(mongodb_batch_olbia, 58).
unreachable(mongodb_batch_olbia, 59).
unreachable(mongodb_batch_olbia, 60).
unreachable(mongodb_batch_olbia, 61).
unreachable(mongodb_batch_olbia, 62).
unreachable(mongodb_batch_olbia, 63).
unreachable(mongodb_batch_olbia, 64).
unreachable(mongodb_batch_olbia, 65).
unreachable(mongodb_batch_olbia, 66).
unreachable(mongodb_batch_olbia, 67).
unreachable(mongodb_batch_olbia, 68).
unreachable(mongodb_batch_olbia, 69).
unreachable(mongodb_batch_olbia, 70).
unreachable(mongodb_batch_olbia, 71).
unreachable(mongodb_batch_olbia, 72).
unreachable(mongodb_batch_olbia, 73).
unreachable(mongodb_batch_olbia, 74).
unreachable(mongodb_batch_olbia, 75).
unreachable(mongodb_batch_olbia, 76).
unreachable(mongodb_batch_olbia, 77).
unreachable(mongodb_batch_olbia, 78).
unreachable(mongodb_batch_olbia, 79).
unreachable(mongodb_batch_olbia, 80).
unreachable(mongodb_batch_olbia, 81).
unreachable(mongodb_batch_olbia, 82).
unreachable(mongodb_batch_olbia, 83).
unreachable(mongodb_batch_olbia, 84).
unreachable(mongodb_batch_olbia, 85).
unreachable(mongodb_batch_olbia, 86).
unreachable(mongodb_batch_olbia, 87).
unreachable(mongodb_batch_olbia, 88).
unreachable(mongodb_batch_olbia, 89).
unreachable(mongodb_batch_olbia, 90).
unreachable(mongodb_batch_olbia, 91).
unreachable(mongodb_batch_olbia, 92).
unreachable(mongodb_batch_olbia, 93).
unreachable(mongodb_batch_olbia, 94).
unreachable(mongodb_batch_olbia, 95).
unreachable(mongodb_batch_olbia, 96).
unreachable(mongodb_batch_olbia, 97).
unreachable(mongodb_batch_olbia, 98).

% Nodes failures

overload(worker3, ram, 31, 98).
