% Deployment
deployedTo(aggregator, large, worker2).
deployedTo(analyzer, large, worker2).
deployedTo(data_gather_olbia, tiny, worker1).
deployedTo(data_gather_torino, tiny, worker1).
deployedTo(gateway, large, main).
deployedTo(mongodb_history, medium, worker3).

% Components failures
unreachable(aggregator, 31).
unreachable(aggregator, 32).
unreachable(aggregator, 33).
unreachable(aggregator, 34).
unreachable(aggregator, 35).
unreachable(aggregator, 36).
unreachable(aggregator, 37).
unreachable(aggregator, 38).
unreachable(aggregator, 39).
unreachable(aggregator, 40).
unreachable(aggregator, 41).
unreachable(aggregator, 42).
unreachable(aggregator, 43).
unreachable(aggregator, 44).
unreachable(aggregator, 45).
unreachable(aggregator, 46).
unreachable(aggregator, 47).
unreachable(aggregator, 48).
unreachable(aggregator, 49).
unreachable(aggregator, 50).
unreachable(aggregator, 51).
unreachable(aggregator, 52).
unreachable(aggregator, 53).
unreachable(aggregator, 54).
unreachable(aggregator, 55).
unreachable(aggregator, 56).
unreachable(aggregator, 57).
unreachable(aggregator, 58).
unreachable(aggregator, 59).
unreachable(aggregator, 60).
unreachable(aggregator, 61).
unreachable(aggregator, 62).
unreachable(aggregator, 63).
unreachable(aggregator, 64).
unreachable(aggregator, 65).
unreachable(aggregator, 66).
unreachable(aggregator, 67).
unreachable(aggregator, 68).
unreachable(aggregator, 69).
unreachable(aggregator, 70).
unreachable(aggregator, 71).
unreachable(aggregator, 72).
unreachable(aggregator, 73).
unreachable(aggregator, 74).
unreachable(aggregator, 75).
unreachable(aggregator, 76).
unreachable(aggregator, 77).
unreachable(aggregator, 78).
unreachable(aggregator, 79).
unreachable(aggregator, 80).
unreachable(aggregator, 81).
unreachable(aggregator, 82).
unreachable(aggregator, 83).
unreachable(aggregator, 84).
unreachable(aggregator, 85).
unreachable(aggregator, 86).
unreachable(aggregator, 87).
unreachable(aggregator, 88).
unreachable(aggregator, 89).
unreachable(aggregator, 90).
unreachable(aggregator, 91).
unreachable(aggregator, 92).
unreachable(aggregator, 93).
unreachable(aggregator, 94).
unreachable(aggregator, 95).
unreachable(aggregator, 96).
unreachable(aggregator, 97).
unreachable(aggregator, 98).
unreachable(analyzer, 31).
unreachable(analyzer, 32).
unreachable(analyzer, 33).
unreachable(analyzer, 34).
unreachable(analyzer, 35).
unreachable(analyzer, 36).
unreachable(analyzer, 37).
unreachable(analyzer, 38).
unreachable(analyzer, 39).
unreachable(analyzer, 40).
unreachable(analyzer, 41).
unreachable(analyzer, 42).
unreachable(analyzer, 43).
unreachable(analyzer, 44).
unreachable(analyzer, 45).
unreachable(analyzer, 46).
unreachable(analyzer, 47).
unreachable(analyzer, 48).
unreachable(analyzer, 49).
unreachable(analyzer, 50).
unreachable(analyzer, 51).
unreachable(analyzer, 52).
unreachable(analyzer, 53).
unreachable(analyzer, 54).
unreachable(analyzer, 55).
unreachable(analyzer, 56).
unreachable(analyzer, 57).
unreachable(analyzer, 58).
unreachable(analyzer, 59).
unreachable(analyzer, 60).
unreachable(analyzer, 61).
unreachable(analyzer, 62).
unreachable(analyzer, 63).
unreachable(analyzer, 64).
unreachable(analyzer, 65).
unreachable(analyzer, 66).
unreachable(analyzer, 67).
unreachable(analyzer, 68).
unreachable(analyzer, 69).
unreachable(analyzer, 70).
unreachable(analyzer, 71).
unreachable(analyzer, 72).
unreachable(analyzer, 73).
unreachable(analyzer, 74).
unreachable(analyzer, 75).
unreachable(analyzer, 76).
unreachable(analyzer, 77).
unreachable(analyzer, 78).
unreachable(analyzer, 79).
unreachable(analyzer, 80).
unreachable(analyzer, 81).
unreachable(analyzer, 82).
unreachable(analyzer, 83).
unreachable(analyzer, 84).
unreachable(analyzer, 85).
unreachable(analyzer, 86).
unreachable(analyzer, 87).
unreachable(analyzer, 88).
unreachable(analyzer, 89).
unreachable(analyzer, 90).
unreachable(analyzer, 91).
unreachable(analyzer, 92).
unreachable(analyzer, 93).
unreachable(analyzer, 94).
unreachable(analyzer, 95).
unreachable(analyzer, 96).
unreachable(analyzer, 97).
unreachable(analyzer, 98).

% Nodes failures

overload(worker2, ram, 31, 98).
